plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/npm"
  - - "semantic-release-expo"
    - versions:
        android: "${increment}"
        ios: "${increment}"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
        - package-lock.json
        - app.json
      message: "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
  - - "@semantic-release/gitlab"
    - gitlabUrl: https://gitlab.com